// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Protocol.proto

package itc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Value                uint32   `protobuf:"varint,1,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	IsLeaf               bool     `protobuf:"varint,2,opt,name=IsLeaf,json=isLeaf,proto3" json:"IsLeaf,omitempty"`
	Left                 *Event   `protobuf:"bytes,3,opt,name=Left,json=left,proto3" json:"Left,omitempty"`
	Right                *Event   `protobuf:"bytes,4,opt,name=Right,json=right,proto3" json:"Right,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_071a0530b1819269, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Event) GetIsLeaf() bool {
	if m != nil {
		return m.IsLeaf
	}
	return false
}

func (m *Event) GetLeft() *Event {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *Event) GetRight() *Event {
	if m != nil {
		return m.Right
	}
	return nil
}

type Id struct {
	Value                uint32   `protobuf:"varint,1,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	IsLeaf               bool     `protobuf:"varint,2,opt,name=IsLeaf,json=isLeaf,proto3" json:"IsLeaf,omitempty"`
	Left                 *Id      `protobuf:"bytes,3,opt,name=Left,json=left,proto3" json:"Left,omitempty"`
	Right                *Id      `protobuf:"bytes,4,opt,name=Right,json=right,proto3" json:"Right,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_071a0530b1819269, []int{1}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Id) GetIsLeaf() bool {
	if m != nil {
		return m.IsLeaf
	}
	return false
}

func (m *Id) GetLeft() *Id {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *Id) GetRight() *Id {
	if m != nil {
		return m.Right
	}
	return nil
}

type Stamp struct {
	Id                   *Id      `protobuf:"bytes,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
	Event                *Event   `protobuf:"bytes,2,opt,name=Event,json=event,proto3" json:"Event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stamp) Reset()         { *m = Stamp{} }
func (m *Stamp) String() string { return proto.CompactTextString(m) }
func (*Stamp) ProtoMessage()    {}
func (*Stamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_071a0530b1819269, []int{2}
}

func (m *Stamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stamp.Unmarshal(m, b)
}
func (m *Stamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stamp.Marshal(b, m, deterministic)
}
func (m *Stamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stamp.Merge(m, src)
}
func (m *Stamp) XXX_Size() int {
	return xxx_messageInfo_Stamp.Size(m)
}
func (m *Stamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Stamp.DiscardUnknown(m)
}

var xxx_messageInfo_Stamp proto.InternalMessageInfo

func (m *Stamp) GetId() *Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Stamp) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "itc.Event")
	proto.RegisterType((*Id)(nil), "itc.Id")
	proto.RegisterType((*Stamp)(nil), "itc.Stamp")
}

func init() { proto.RegisterFile("Protocol.proto", fileDescriptor_071a0530b1819269) }

var fileDescriptor_071a0530b1819269 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x2b, 0x00, 0x31, 0x84, 0x98, 0x33, 0x4b, 0x92, 0x95, 0xca, 0xb9,
	0x58, 0x5d, 0xcb, 0x52, 0xf3, 0x4a, 0x84, 0x44, 0xb8, 0x58, 0xc3, 0x12, 0x73, 0x4a, 0x53, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x78, 0x83, 0x58, 0xcb, 0x40, 0x1c, 0x21, 0x31, 0x2e, 0x36, 0xcf, 0x62,
	0x9f, 0xd4, 0xc4, 0x34, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0xb6, 0x4c, 0x30, 0x4f, 0x48,
	0x8e, 0x8b, 0xc5, 0x27, 0x35, 0xad, 0x44, 0x82, 0x59, 0x81, 0x51, 0x83, 0xdb, 0x88, 0x4b, 0x2f,
	0xb3, 0x24, 0x59, 0x0f, 0x6c, 0x4e, 0x10, 0x4b, 0x4e, 0x6a, 0x5a, 0x89, 0x90, 0x02, 0x17, 0x6b,
	0x50, 0x66, 0x7a, 0x46, 0x89, 0x04, 0x0b, 0x86, 0x02, 0xd6, 0x22, 0x90, 0x84, 0x52, 0x1e, 0x17,
	0x93, 0x67, 0x0a, 0x89, 0xb6, 0x4a, 0xa3, 0xd8, 0xca, 0x0e, 0x36, 0xd4, 0x33, 0x05, 0x6a, 0xa5,
	0x2c, 0xaa, 0x95, 0x70, 0x59, 0xa8, 0x7d, 0x4e, 0x5c, 0xac, 0xc1, 0x25, 0x89, 0xb9, 0x05, 0x42,
	0xe2, 0x20, 0x8b, 0xc1, 0xf6, 0x21, 0x29, 0x62, 0xca, 0x4c, 0x01, 0xb9, 0x19, 0xec, 0x42, 0xb0,
	0xa5, 0x68, 0x6e, 0x4e, 0x05, 0x51, 0x49, 0x6c, 0xe0, 0x80, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xb0, 0x86, 0x23, 0xad, 0x4a, 0x01, 0x00, 0x00,
}
